### ISSUE TITLE
EVT_CLIENT_UPDATE

### ISSUE THREAD

**Issue by thomasleveil** [danielepantaleone/b3-plugin-geolocation#1]
for some games when `EVT_CLIENT_AUTH` occurs the ip address is not known. It is retrieved later on and a  `EVT_CLIENT_UPDATE` is fired. It would be nice to react to this event as well.

But I guess you would need to check is `.location` is set before querying the geo services to avoid unnecessary calls.

**Comment by danielepantaleone** [comment]
Thanks for the tip. I'll make the changes tomorrow. 

Inviato da iPhone
